### ISSUE TITLE
Does WORDPRESS_SITE_URL matters?

### ISSUE THREAD

**Issue by delmicio** [TrafeX/docker-wordpress#10]
There is currently a environment variable called `WORDPRESS_SITE_URL` 

`WORDPRESS_SITE_URL: http://localhost`

How should it be used in production?

**Comment by jhabdas** [comment]
@delmicio This resource may be helpful for you. When in doubt, experiment.

https://12factor.net/config

**Comment by TrafeX** [comment]
You can probably leave it out. It overrides the site url which you can define in the WP settings.
I used it to enforce the use of HTTPS, but WordPress should normally autodetect this

**Comment by jhabdas** [comment]
@delmicio why did you give me a 👎 for trying to help you. That's just rude bro.
