### ISSUE TITLE
How to secure nginx with letsencrypt?

### ISSUE THREAD

**Issue by berkedel** [TrafeX/docker-wordpress#11]
I stumbled upon [this article](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04). I wonder if a built-in letsencrypt client that automates free SSL server certificate generation and renewal processes can be done in this build.

**Comment by jhabdas** [comment]
@berkedel fwiw certs generated with LE require periodic renewal, which requires a cron job to periodically check and renew the cert (assuming the renewal is automated). not sure if you've found any examples you could share here which already use docker—having one would be much more useful. head here for some related discussion: https://habd.as/zero-to-http-2-aws-hugo/#comment-3148930013

**Comment by kabudu** [comment]
@berkedel This might help!

https://github.com/jwilder/nginx-proxy

**Comment by berkedel** [comment]
Thanks all. After trial and error, I figured out how to setup the certificate. [This article](https://miki725.github.io/docker/crypto/2017/01/29/docker+nginx+letsencrypt.html) helped me a lot.

**Comment by jhabdas** [comment]
Thanks for sharing @berkedel. Hope the process is repeatable. That for me has always been the pinch with Certbot. Looking forward to hearing some success stories in 3 months.

P.s. Have you looked at Caddy? https://caddyserver.com
