### ISSUE TITLE
Logout from WooCommerce's my account page is not working

### ISSUE THREAD

**Issue by berkedel** [TrafeX/docker-wordpress#12]
I install WooCommerce plugin and found a strange behavior. Whenever I try to logout from my account page (the endpoint is `/my-account/customer-logout/?_wpnonce=db71110b59`) does not seem to invalidate my current session. But if I try to logout from wordpress `wp-login.php` (the endpoint is `/wp-login.php?action=logout&_wpnonce=6d96f8c37a`, it works. How to solve this problem? Is this related to `nginx` configuration?

**Comment by TrafeX** [comment]
Hi, thanks for reporting this issue. Did you try the latest version?
I fixed a issue with the WP API earlier with this commit: https://github.com/TrafeX/docker-wordpress/commit/44f361814d5c8e363b3792fbe5443544816d98d1
Maybe that was the same issue?
If you already used the latest version then I'll have to see if I can reproduce this to fix it. Let me know!

**Comment by berkedel** [comment]
Yes, I'm using the latest version.

**Comment by TrafeX** [comment]
There was indeed an issue with the nginx config; the query string wasn't correctly formatted because the `?` was missing. This was causing the logout issue.

This is fixed in the latest release: https://github.com/TrafeX/docker-wordpress/releases/tag/4.8.2-1

**Comment by cittrarasu** [comment]
How to use this file..please explain step by step  https://github.com/TrafeX/docker-wordpress/releases/tag/4.8.2-1
