### ISSUE TITLE
Check if WordPress Database exists

### ISSUE THREAD

**Issue by gurumark** [TrafeX/docker-wordpress#18]
Hi,
Thanks for the image.
Is it possible to add a new feature checking if WordPress database exists and if not create it using the credential passed as env variables?

Thanks!

**Comment by TrafeX** [comment]
Hi gurumark,

That would be possible, but goes beyond the responsibility of this image. It's up to the orchestrator (the application that deploys this image) to make sure the dependencies like a database is available.
If you use the [MariaDB](https://hub.docker.com/_/mariadb/) image then you can set the `MYSQL_DATABASE` environment variable to specify which database to create on startup.

I hope this helps!
