### ISSUE TITLE
PHP errors not redirect to docker logs

### ISSUE THREAD

**Issue by gurumark** [TrafeX/docker-wordpress#23]
Hi,
The default configuration does not display any PHP errors in the docker logs.

docker container logs CONTAINER-NAME -f  only shows the access log but not any PHP errors.

Is there anything I should be setting to make it work?

thanks in advance.

**Comment by gurumark** [comment]
It turns out that fpm-pool.conf does not have:
php_admin_value[error_log] = /var/www/log/php-error.log
php_admin_flag[log_errors] = on
php_admin_value[error_reporting] = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED

**Comment by TrafeX** [comment]
Hi,

That's strange, it should show errors as configured in the php.ini: https://github.com/TrafeX/docker-wordpress/blob/master/config/php.ini#L2. And `log_errors` is by default enabled.
Are you sure you needed this to see errors?

**Comment by gurumark** [comment]
Yes, It took me a few hours to figure this out. Unless I put the following code in the fpm-pool.conf (php.ini did not work)  file. It will not echo anything the docker logs:

php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/nginx/error.log
php_admin_value[error_reporting] = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED

If I missed something, please let me know.
