### ISSUE TITLE
Throws 404 error after adding new theme 

### ISSUE THREAD

**Issue by hkaraoglu** [TrafeX/docker-wordpress#27]
If we add new theme into wordpress on a running docker container, it throws 404 error while requesting css, js files. How can we solve this?

<img width="700" alt="Screen Shot 2020-03-09 at 23 14 45" src="https://user-images.githubusercontent.com/7407515/76253741-47d6e380-625c-11ea-8314-0496377d351b.png">

**Comment by TrafeX** [comment]
Hi @hkaraoglu ,

That could basically be anything :wink: 
Can you go into the container to see the files are actually there?
```
docker exec -ti <your containernname> sh
cd /var/www
ls -l themes/astra
```

**Comment by hkaraoglu** [comment]
@TrafeX Yes . I see the files.

**Comment by TrafeX** [comment]
Hi @hkaraoglu ,

Sorry it's been a while. Where you able to resolve this issue?
