### ISSUE TITLE
"Error establishing a database connection" after Port change

### ISSUE THREAD

**Issue by jbarr** [TrafeX/docker-wordpress#30]
I issued the provided command with the port changed from 80:80 to 8080:80 and everything started up properly, however when I navigated to localhost:8080, it throws a "Error establishing a database connection" error.

**Comment by TrafeX** [comment]
@jbarr What exactly did you do? Did you used `docker-compose`?

**Comment by molecula451** [comment]
check that your mariadb container is running, kill containers and re-run <code> docker-compose up</code>

**Comment by TrafeX** [comment]
Hi @jbarr,

I hope you were able to resolve the issue. I'm closing this ticket since it's not active anymore.
Feel free to open a new ticket if you still experience this issue.
