### ISSUE TITLE
Supervisord.conf

### ISSUE THREAD

**Issue by Fitz22** [TrafeX/docker-wordpress#31]
Hello

I've a problem when i launch your container.
In my logs i see 
`CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.`

I try to add `user=root` in config/supervisord.conf in the [supervisord] section but nothing change.

Do you have a solution?

Thank you for your work

**Comment by TrafeX** [comment]
Hi @Fitz22,

That warning is normal. It isn't affecting supervisor, it's just running normally.
To really resolve this I'll need to switch to a different init daemon (s6 for example). But for now this should be good.
