### ISSUE TITLE
depoying in ECS

### ISSUE THREAD

**Issue by ThejusAP** [TrafeX/docker-wordpress#32]
Hi Sir,

I have seen your code and its really awesome.
Since I am just a beginner and am learning devops recently , I would like to know how to deploy the same in an amazon ECS

I have pushed the image to amazon ECR and I need to provision docker containers now using ECS , Would you please show me a way for the same.

**Comment by ThejusAP** [comment]
have tried to run the compose file locally, it was running fine, and now trying to deploy it to ECS

**Comment by TrafeX** [comment]
Hi @ThejusAP,

I think it's best to start with a tutorial on ECS first, like this: https://medium.com/boltops/gentle-introduction-to-how-aws-ecs-works-with-example-tutorial-cea3d27ce63d
Then you should be able to get this container up&running on ECS.

If you have specific issues with this container on ECS, let me know!
