### ISSUE TITLE
Support php8 ?

### ISSUE THREAD

**Issue by munjalpatel** [TrafeX/docker-wordpress#33]
Hey @TrafeX nice work!

Quick question, do you plan to support PHP8 based setup?
If not, do you foresee any issues using this same setup with PHP8?

Thanks!

**Comment by TrafeX** [comment]
Hi @munjalpatel,

Yes I'm planning on supporting PHP8. It's in Alpine Linux 1.13 since a few days and I don't see any issues with upgrading.

**Comment by TrafeX** [comment]
A bit later than planned, but here it is: https://github.com/TrafeX/docker-wordpress/releases/tag/5.7.2-1
Enjoy! :tada:
