### ISSUE TITLE
wp-secrets.php only gets generated when the volume is empty

### ISSUE THREAD

**Issue by nickjanssen** [TrafeX/docker-wordpress#36]
Hi, wp-secrets.php only gets generated when the volume is empty. However, once the volume is there and the container has to restart for whatever reason (e.g. when moving a pod to another node on k8s) the wp-secrets.php won't be recreated since the volume already exists.

I think it should be passed with a separate volume instead.

https://github.com/TrafeX/docker-wordpress/blob/8ca167b0a176e5e557795f31298b5209d20a4d9e/entrypoint.sh#L14

**Comment by TrafeX** [comment]
Hi @nickjanssen,

The idea is that `/var/www/wp-content` is mounted on a persistent volume, because there the plugins, themes and uploads are stored as well.  You also don't want to re-generate the secrets because than you're not able to login WordPress anymore due to the changed salt.

**Comment by TrafeX** [comment]
Hi @nickjanssen,

I'm going to close this issue due to inactivity. Let me know if you have any other questions!

**Comment by TrafeX** [comment]
See the latest updates in https://github.com/TrafeX/docker-wordpress/issues/42, the issue should be resolved. Thanks for reporting!
