### ISSUE TITLE
Can't start up WP container due to entrypoint.sh error

### ISSUE THREAD

**Issue by daniel-dan1** [TrafeX/docker-wordpress#37]
Hello! I have runned previous versions of this image without issues, but since the last update to WP v6.1 I am getting an error that drops the WP container a second after it starts. 
Error in the log reads: 
`exec /usr/local/bin/entrypoint.sh: no such file or directory`

Building without the ENTRYPOINT line solves the startup issue, however we don't get that script executed. The files get copied correctly and has +x access mode.

I am running Docker Desktop v 4.12.0 in Windows 11.

**Comment by daniel-dan1** [comment]
Found the issue. Seems the .sh scripts were edited in Windows on this commit and contained the CRLF end of line. I changed it to LF (what linux expects) with Notepad++ and they started working correctly. 

Just in case, I attach both .sh corrected scripts. I'll also try to contribute them through my fork.

Thanks!
[sh.zip](https://github.com/TrafeX/docker-wordpress/files/9939265/sh.zip)

**Comment by TrafeX** [comment]
Hi @daniel-dan1,

That's a strange issue. But I'm sure all the files in this repo use LF line endings. You can see that;

```
$ git ls-files --eol
..
i/lf    w/lf    attr/                 	entrypoint.sh
```
I think something else is causing this. Can you show the exact command you're using to run this container?

**Comment by daniel-dan1** [comment]
Hi @TrafeX,

You are right. The problem was on my side. My Windows box was using the default git config, so it was converting all eol's from LF to CRLF when cloning/pulling from GitHub.
I configured core.autocrlf=false, did a clean clone, and all files are now end in LF, including the entrypoint script.

`git ls-files --eol
..
i/lf    w/lf    attr/                   entrypoint.sh`

Thanks for your reply and good job with this repo!
Dan.

**Comment by TrafeX** [comment]
Good to hear you could solve it! :+1:
