### ISSUE TITLE
WP-Content Folder

### ISSUE THREAD

**Issue by raisiqueira** [TrafeX/docker-wordpress#4]
Who i work with the wp-content folder? example for developer a theme with local access

**Comment by TrafeX** [comment]
Hi raisiqueira,

I'm not sure if I understand your question correctly. Do you want to know how to access the wp-content folder?
This image is meant to have themes and plugins installed via the WordPress interface.
If you want to include a custom theme or plugin you can fork this project and add you custom theme to `/var/www/`. Nginx is configured to look in that folder for `wp-content` files.

Hope this answers your question, if not, let me know!
