### ISSUE TITLE
Explicitly setting WP_DEBUG and WP_DEBUG_DISPLAY to false makes them true

### ISSUE THREAD

**Issue by Morpheus636** [TrafeX/docker-wordpress#41]
Explicitly setting the environment variables to false sets the options to true within Wordpress.

At the very least, this should be documented behavior. Ideally, a fix would check the value of the environment variables and not just whether they are set.

**Comment by TrafeX** [comment]
Hi @Morpheus636,

Good catch! I've fixed it this way: https://github.com/TrafeX/docker-wordpress/commit/29d8ac8f3e2528c263503df1ee962fa1449eaaf8
It's fixed in the latest release.
