### ISSUE TITLE
Error In Browser running wordpress docker image!

### ISSUE THREAD

**Issue by BigDC** [TrafeX/docker-wordpress#5]
Hey, whenever I try to run your WordPress docker image, I get this error in my web browser...
## "**Error establishing a database connection**"
Please help?
-BigDC

**Comment by TrafeX** [comment]
Hi, sorry for the late response! Need to tweak my notification settings apparently.

How did you start the Docker container? Do you have a separate container for the database?

**Comment by TrafeX** [comment]
Let me know if you still have any issues! For now I'll close this.

**Comment by jhabdas** [comment]
For the record I experienced this yesterday as well but I was doing naughty things with Docker Cloud to create this issue.
