### ISSUE TITLE
File directory access with volume switch

### ISSUE THREAD

**Issue by Bulok01** [TrafeX/docker-wordpress#57]
I would like to be able to access the directory where the .htaccess file is installed in order to further secure my site but I have not been able to find where it is stored!
 Could we choose, in the same way as wp-content, where the site files are installed? 

Making a "volume" link to /var/www/html did not work for me.

**Comment by TrafeX** [comment]
Hi @Bulok01,

This Docker image is using Nginx which doesn't support `.htaccess`.
The configuration can be found in [nginx.conf](https://github.com/TrafeX/docker-wordpress/blob/master/config/nginx.conf)
