### ISSUE TITLE
Is links key necessary?

### ISSUE THREAD

**Issue by jhabdas** [TrafeX/docker-wordpress#7]
https://docs.docker.com/compose/compose-file/compose-versioning/#version-2

> The `depends_on` option can be used in place of links to indicate dependencies between services and startup order.

Seems `links` may no longer be necessary. Have you tried pulling it?

**Comment by TrafeX** [comment]
You're right! I removed it: https://github.com/TrafeX/docker-wordpress/commit/5961586274cfa11db383f7b285df03b1d6ae54a2

Thanks!
