### ISSUE TITLE
Thoughts on Swarming?

### ISSUE THREAD

**Issue by jhabdas** [TrafeX/docker-wordpress#8]
https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

First off, your work here absolutely splendid. And I don't want to take too much of your time. I'm just curious if you've considered or would consider what it might take to move to Compose 3 and allow scaling for WP instances distributed in a swarm.

With Galera it looks like Maria DB is also setting up for distributed clustering, which, with a version 3, should tee others up to allow the database to be scaled in a swarm.

Is this crazy? IDK but here's a prototype: https://github.com/jlk/wordpress-swarm

**Aside:** I noticed the latest stable of Maria DB introduces the opportunity to do some cool stuff with JSON and also the ability to swap out Inno with the same tool powering http://rocksdb.org/, which has some potential to decrease footprint of the store as well as memory consumption. Obviously rolling DB versions forward isn't something one ought to be doing frequently - or so I'd assume - so I'm just dropping this in here for the sake of consideration WRT swarming.

**Comment by TrafeX** [comment]
Moving to Docker Compose v3 isn't a problem. But making this Docker container scale is a whole different story. The problem does not lie in the Docker setup but in WordPress. 
You need to store assets & media on something outside of the container (Amazon S3 for example). And you probably want the themes & plugins under version control and build the container images from that source. This is out of scope for this Docker container because it's hard to make a "one size fits all" solution.

**Comment by jhabdas** [comment]
Thanks. Good to know. Would love to see Compose 3. I tried to write convert it on my end but still need to learn a little more about composer and your goals here. 

Sounds like there's room for some creative work.  Once the compose is moved to version three I'll see what I can do.  Thank you for this fine piece of work.

**Comment by TrafeX** [comment]
Moving the docker-compose.yml to version 3 is not more than chtanging the version number in the file. It's already compatible. So I'm not sure what you want to do?

**Comment by jhabdas** [comment]
Moving to v3 enables the stack to be stood up using the stack subcommand for Docker, eliminating the need for an additional installation of docker-compose. If it's as easy as suggested, sounds like all that'd be needed are some doc updates and a version bump in the compose file. It's been long enough now I don't remember why I had trouble upgrading myself. Still learning. YMMV. But the actionable step is to upgrade and drop docker-compose.

**Comment by TrafeX** [comment]
I'm closing this issue as I don't see anything I can do. Let me know if you have a different opinion on that!

**Comment by jhabdas** [comment]
Idea was to change to version 3 to support swarming. I think you've suggested—albeit somewhat cryptically—you'll leave that labor to someone else. No worries. Hope to see you bump in the future.
