### ISSUE TITLE
Backup and Restore?

### ISSUE THREAD

**Issue by jhabdas** [TrafeX/docker-wordpress#9]
In his 2016 article titled [How to deploy a wordpress blog on docker cloud in less than 5 minutes](https://medium.com/@aherve/how-to-deploy-a-wordpress-blog-on-docker-cloud-in-less-than-5-minutes-9cd7c30cbdb5), Aurélien Hervé describes a simple technique for enabling backup and restore functionality for data held in the database as well as the `wp-content` directories.

His method uses Docker Cloud and Compose v3 to achieve this capability. While not necessarily required here, I'm curious to hear your thoughts on making backup and restore functionality possible within the current toolset so critical site backup and restore functionality may be achieved using an external provider and in a scripted manner.

If this is already possible, could you enlighten us to your technique?

**Comment by TrafeX** [comment]
For my own WordPress sites I only have "disaster recovery". The wp-content folder and the storage for MySQL are both mounted volumes on the host system. From that volumes I make a backup every day.
When everything is gone and I only have my backups left I just spinup the containers(from Docker Hub) with the same volumes and I'm up&running again.
There are lots of other ways of doing this, but this works for me. I don't want this Docker image to be depended on Docker Cloud. The docker-compose.yml in this repo is just an example, you should create your own as described in the article you mention.

**Comment by jhabdas** [comment]
Suksma
